# docker-compose.yml

version: '3.8'

services:

  redis:
    image: redis
    ports:
      - 6739:6739
    networks:
      - nginx_network

  generate_image:
    image: amouat/dnmonster
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - nginx_network

  web:
    build: .
    command: >
      sh -c "alembic revision --autogenerate -m "init"&&
             alembic upgrade head &&
             uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    expose:
      - 8000
    depends_on:
      - db
      - redis
      - generate_image
    env_file:
      - .env
    environment:
      - IMAGEAPI=http://generate_image:8080
      - REDIS=redis
      - POSTGRES_HOST=db
    networks:
      - nginx_network
    restart: on-failure

  proxy:
    image: nginx:alpine
    depends_on:
      - web
      - db
      - redis
      - generate_image
    ports:
      - 80:80
    volumes:
      #volume mount:"Host OS path:Path in the container"
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - nginx_network

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

volumes:
  postgres_data: