# docker-compose.yml

version: '3.8'

services:
  redis:
    image: redis
    ports:
      - 6739:6739
  generate_image:
    image: amouat/dnmonster
    ports:
      - 8080:8080
  web:
    build: .
    command: >
      sh -c "alembic revision --autogenerate -m "initial" &&
             alembic upgrade head &&
             uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - 8008:8000
    depends_on:
      - db
      - redis
      - generate_image
    env_file:
      - .env
    restart: on-failure

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  postgres_data: