"""delete rounds

Revision ID: 6f91597ce177
Revises: cce027aac7ae
Create Date: 2022-02-01 17:45:30.448043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f91597ce177'
down_revision = 'cce027aac7ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'salt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salt', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
