"""delete rounds

Revision ID: cce027aac7ae
Revises: 3e73ffc5ae8b
Create Date: 2022-02-01 11:58:23.490922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce027aac7ae'
down_revision = '3e73ffc5ae8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rounds')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rounds', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
